---
- name: Install docker-machine-kvm
  get_url:
    url: https://github.com/dhiltgen/docker-machine-kvm/releases/download/v{{docker_machine_kvm_version}}/docker-machine-driver-kvm
    dest: "{{ bin_dir }}/docker-machine-driver-kvm"
    mode: 0755
  become: yes  
...
