---
- name: Get minishift {{ minishift_version }}
  get_url:
      url: https://github.com/minishift/minishift/releases/download/v{{minishift_version }}/minishift-{{ minishift_version }}-linux-amd64.tgz
      dest: /tmp
      mode: 0777

- name: Extract archive
  unarchive:
    src: /tmp/minishift-{{ minishift_version }}-linux-amd64.tgz
    dest: /tmp
    mode: 0777

- name: Move minishift to bin
  copy:
    src: /tmp/minishift-{{ minishift_version }}-linux-amd64/minishift
    dest: "{{ bin_dir }}"
    mode: 0755
  become: yes
...
